package com.uok.sams.models;

public enum Province {
    CP, EP, NP, SP, WP, NWP, NCP, UP, SBP
}

enum District{
    JAFFNA, KILINOCHCHI, MANNAR, MULLAITIVU, VAVUNIYA, PUTTALAM, KURUNEGALA, GAMPAHA, COLOMBO, KALUTARA, ANURADHAPURA,
    POLONNARUWA, MATALE, KANDY, NUWARA_ELIYA, KEGALLE, RATNAPURA, TRINCOMALEE, BATTICALOA, AMPARA, BADULLA, MONARAGALA,
    HAMBANTOTA, MATARA, GALLE
}
